title: Welcome!
logo: img/professional_pic.jfif
author: Corbin Couger
email: corbin.0007@yahoo.com
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  social_links:
    - { platform: linkedin,  user_url: "https://www.linkedin.com/in/corbincouger/" }

show_excerpts: false
